src:
  - changed-files:
    - any-glob-to-any-file: 'src/**'

tests:
  - changed-files:
    - any-glob-to-any-file: 'tests/**'

docs:
  - changed-files:
    - any-glob-to-any-file: 'docs/**'

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

samples:
  - changed-files:
    - any-glob-to-any-file: 'samples/**'

benchmarks:
  - changed-files:
    - any-glob-to-any-file: 'benchmarks/**'
