// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace WorkflowFramework.Dashboard.UITests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "UI")]
    public partial class WorkflowDesignerFeature : object, global::Xunit.IClassFixture<WorkflowDesignerFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "UI"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Workflow Designer", "  As a user I can visually design workflows using the drag-and-drop designer", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "WorkflowDesigner.feature"
#line hidden
        
        public WorkflowDesignerFeature(WorkflowDesignerFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/WorkflowDesigner.feature", @"@UI
Feature: Workflow Designer
  As a user I can visually design workflows using the drag-and-drop designer

  @screenshot:designer-overview
  Scenario: View empty designer on launch
    Given the dashboard is running
    When I navigate to the designer
    Then I should see the step palette on the left
    And I should see an empty canvas
    And I should see the properties panel on the right

  @screenshot:step-palette
  Scenario: Search step palette
    Given the dashboard is running
    When I navigate to the designer
    And I type ""conditional"" in the step search
    Then I should see filtered steps containing ""conditional""

  @screenshot:properties-panel
  Scenario: Select a node and view properties
    Given the dashboard is running
    And I have a workflow with an action step
    When I click on the action step node
    Then the properties panel should show the step configuration

  Scenario: SubWorkflow step shows saved workflow suggestions
    Given the dashboard is running
    And I have a workflow with a SubWorkflow step
    When I select the SubWorkflow step
    Then the properties panel should show saved workflow suggestions including ""Child Flow""
    When I choose saved workflow ""Child Flow""
    Then the SubWorkflow reference should be ""Child Flow""

  @screenshot:toolbar
  Scenario: View toolbar
    Given the dashboard is running
    When I navigate to the designer
    Then the toolbar should show save, run, validate, and settings buttons
", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/WorkflowDesigner.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(2, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), "@UI", "421b6e9205620d538bdc0821ee7b8650")}), "en", "Feature", "Workflow Designer", "  As a user I can visually design workflows using the drag-and-drop designer", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(5, new System.Nullable<long>(3)), "@screenshot:designer-overview", "5b3211a45c8e945f9ae6abf18c426910")}), "Scenario", "View empty designer on launch", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "446265111b2951588dcf0a464f4dea58"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I navigate to the designer", null, null, "e5fcb51f60fd0b5ebaf0edcb56683a49"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see the step palette on the left", null, null, "18fc6659bc9dbc5c91246994b063774f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I should see an empty canvas", null, null, "1cdf9b1fc1c89451a987f04e313f6c91"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I should see the properties panel on the right", null, null, "c860c4a9a8a68f519a1f20fff99c080b")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "40c777c13229ef588d80742916815b1a")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(3)), "@screenshot:step-palette", "35140d9a766922599af91f0f87a0d97a")}), "Scenario", "Search step palette", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "2d4e2882db2cda578bc931bfd8d7a434"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I navigate to the designer", null, null, "569e310f1ee19150a3caa507b53abbb9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I type \"conditional\" in the step search", null, null, "746ac995e3b46f51826a13ca4486050b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see filtered steps containing \"conditional\"", null, null, "89760381a03998539b990acf5d608441")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "b0624e9871af1b579aaac075a77f799f")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(3)), "@screenshot:properties-panel", "c6581724e852785c8bddfe0d2e5605d9")}), "Scenario", "Select a node and view properties", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "ab4bda08bcb6b351856b1c3258051d8a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I have a workflow with an action step", null, null, "38c205b734140c5cb03e4d33d18377f7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I click on the action step node", null, null, "5ea375f9a9af7f53b0cbb427e737cd06"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the properties panel should show the step configuration", null, null, "e5a9ac555dde615fb9385d336ed1c20f")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "619b1071a6c70b528bf9d17d7eac0624")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "SubWorkflow step shows saved workflow suggestions", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "172337482025ec5fa67c4c56cbd4c009"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I have a workflow with a SubWorkflow step", null, null, "6a3e72d0916dff50ab2a15a4e2128894"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I select the SubWorkflow step", null, null, "3c8018f3be628c5cb86c4f19e6ddee16"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the properties panel should show saved workflow suggestions including \"Child Flow" +
                                                            "\"", null, null, "434d54e4c38c8753b69b3b22dab53c12"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I choose saved workflow \"Child Flow\"", null, null, "f5bf4353e983c5549eb9229c415fa761"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the SubWorkflow reference should be \"Child Flow\"", null, null, "d507151b1baed95e8c6bd8a1e67f1ac9")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "3ff08edc5aeaed518464cd3990ed8fe6")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(3)), "@screenshot:toolbar", "a60703f941de585a826205f006410ac6")}), "Scenario", "View toolbar", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "b620b1353519075499d43ab51e273e9f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I navigate to the designer", null, null, "2046e9a624851b58a78c91ba6bab121f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the toolbar should show save, run, validate, and settings buttons", null, null, "874ad90357065059a949df96579a92eb")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "f43b40b1c6cccb5daee7a0bf9739d060"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("657f1d766fcae752b3002d67b46813a4", "Features/WorkflowDesigner.feature", "View empty designer on launch", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "446265111b2951588dcf0a464f4dea58"}), "8530e183472b98578f9150d67a724346", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e5fcb51f60fd0b5ebaf0edcb56683a49"}), "eae7f211a1482356b02286ed219e6da2", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I navigate to the designer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "18fc6659bc9dbc5c91246994b063774f"}), "ead427b5d484d45eab3420b0c88dcc55", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see the step palette on the left"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1cdf9b1fc1c89451a987f04e313f6c91"}), "4b780eafe31fa455b0c42895c26e9877", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see an empty canvas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c860c4a9a8a68f519a1f20fff99c080b"}), "16ba992214db1d509e4edc415df634d5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see the properties panel on the right")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "421b6e9205620d538bdc0821ee7b8650"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@screenshot:designer-overview", "5b3211a45c8e945f9ae6abf18c426910")}), new System.Collections.Generic.List<string>(new string[] {
                                        "40c777c13229ef588d80742916815b1a"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("1318e116a5b8c4538d1c605ad9ccc162", "Features/WorkflowDesigner.feature", "Search step palette", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2d4e2882db2cda578bc931bfd8d7a434"}), "8ed8b537b28c24578c00a98056a75884", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "569e310f1ee19150a3caa507b53abbb9"}), "7f08b116ad4a495ab0396fd1ba4fdd7a", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I navigate to the designer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "746ac995e3b46f51826a13ca4486050b"}), "860bc7d248d37c5198c83ba8100654f4", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I type \"conditional\" in the step search"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "89760381a03998539b990acf5d608441"}), "00a75a707f489f5d94abf0f937ac4fba", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see filtered steps containing \"conditional\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "421b6e9205620d538bdc0821ee7b8650"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@screenshot:step-palette", "35140d9a766922599af91f0f87a0d97a")}), new System.Collections.Generic.List<string>(new string[] {
                                        "b0624e9871af1b579aaac075a77f799f"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("d4c3d0f257c7b45388c1efc4eb9a673b", "Features/WorkflowDesigner.feature", "Select a node and view properties", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab4bda08bcb6b351856b1c3258051d8a"}), "8e48f39aa85f6750a7ca31dc881d54ee", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "38c205b734140c5cb03e4d33d18377f7"}), "dd578d09aa377359b7723c5320cbc806", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I have a workflow with an action step"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5ea375f9a9af7f53b0cbb427e737cd06"}), "820de3e8267d1054baa05c9aab1dc3bc", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I click on the action step node"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e5a9ac555dde615fb9385d336ed1c20f"}), "26e321614619045089dc0f1ee422657e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the properties panel should show the step configuration")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "421b6e9205620d538bdc0821ee7b8650"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@screenshot:properties-panel", "c6581724e852785c8bddfe0d2e5605d9")}), new System.Collections.Generic.List<string>(new string[] {
                                        "619b1071a6c70b528bf9d17d7eac0624"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3510aceded97d258b4d394be8e02dea8", "Features/WorkflowDesigner.feature", "SubWorkflow step shows saved workflow suggestions", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "172337482025ec5fa67c4c56cbd4c009"}), "1ff3b83e99c9c6578ab51e160487145f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6a3e72d0916dff50ab2a15a4e2128894"}), "4f97ff288cb36e5cabb045f15e00fe6f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I have a workflow with a SubWorkflow step"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3c8018f3be628c5cb86c4f19e6ddee16"}), "db09bbeb135c0a5397646f8f5f344c71", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I select the SubWorkflow step"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "434d54e4c38c8753b69b3b22dab53c12"}), "19b41c77b19a9352bc21bf0dd5e4ba45", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the properties panel should show saved workflow suggestions including \"Child Flow" +
                                                "\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f5bf4353e983c5549eb9229c415fa761"}), "fd763194ca71a155bd7850829f5bc907", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I choose saved workflow \"Child Flow\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d507151b1baed95e8c6bd8a1e67f1ac9"}), "f019f76ba107b05d93b69846074aa8a7", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the SubWorkflow reference should be \"Child Flow\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "421b6e9205620d538bdc0821ee7b8650")}), new System.Collections.Generic.List<string>(new string[] {
                                        "3ff08edc5aeaed518464cd3990ed8fe6"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("94da8f3b28a06155bc4c4b7a01bf877e", "Features/WorkflowDesigner.feature", "View toolbar", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b620b1353519075499d43ab51e273e9f"}), "d432d6e26a57e453816c8386532f7b5b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2046e9a624851b58a78c91ba6bab121f"}), "ae69be88c7975759a9fbd7fd693f5e6f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I navigate to the designer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "874ad90357065059a949df96579a92eb"}), "00679e5a0bab825480635bfe74f6260b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the toolbar should show save, run, validate, and settings buttons")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "421b6e9205620d538bdc0821ee7b8650"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@screenshot:toolbar", "a60703f941de585a826205f006410ac6")}), new System.Collections.Generic.List<string>(new string[] {
                                        "f43b40b1c6cccb5daee7a0bf9739d060"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(WorkflowDesignerFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(WorkflowDesignerFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(WorkflowDesignerFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="View empty designer on launch")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Designer")]
        [global::Xunit.TraitAttribute("Description", "View empty designer on launch")]
        [global::Xunit.TraitAttribute("Category", "screenshot:designer-overview")]
        public async global::System.Threading.Tasks.Task ViewEmptyDesignerOnLaunch()
        {
            string[] tagsOfScenario = new string[] {
                    "screenshot:designer-overview"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View empty designer on launch", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.WhenAsync("I navigate to the designer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.ThenAsync("I should see the step palette on the left", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 10
    await testRunner.AndAsync("I should see an empty canvas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.AndAsync("I should see the properties panel on the right", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Search step palette")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Designer")]
        [global::Xunit.TraitAttribute("Description", "Search step palette")]
        [global::Xunit.TraitAttribute("Category", "screenshot:step-palette")]
        public async global::System.Threading.Tasks.Task SearchStepPalette()
        {
            string[] tagsOfScenario = new string[] {
                    "screenshot:step-palette"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search step palette", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
    await testRunner.WhenAsync("I navigate to the designer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
    await testRunner.AndAsync("I type \"conditional\" in the step search", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.ThenAsync("I should see filtered steps containing \"conditional\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Select a node and view properties")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Designer")]
        [global::Xunit.TraitAttribute("Description", "Select a node and view properties")]
        [global::Xunit.TraitAttribute("Category", "screenshot:properties-panel")]
        public async global::System.Threading.Tasks.Task SelectANodeAndViewProperties()
        {
            string[] tagsOfScenario = new string[] {
                    "screenshot:properties-panel"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Select a node and view properties", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
    await testRunner.AndAsync("I have a workflow with an action step", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.WhenAsync("I click on the action step node", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("the properties panel should show the step configuration", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="SubWorkflow step shows saved workflow suggestions")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Designer")]
        [global::Xunit.TraitAttribute("Description", "SubWorkflow step shows saved workflow suggestions")]
        public async global::System.Threading.Tasks.Task SubWorkflowStepShowsSavedWorkflowSuggestions()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SubWorkflow step shows saved workflow suggestions", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 29
    await testRunner.AndAsync("I have a workflow with a SubWorkflow step", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
    await testRunner.WhenAsync("I select the SubWorkflow step", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
    await testRunner.ThenAsync("the properties panel should show saved workflow suggestions including \"Child Flow" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 32
    await testRunner.WhenAsync("I choose saved workflow \"Child Flow\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
    await testRunner.ThenAsync("the SubWorkflow reference should be \"Child Flow\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="View toolbar")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Designer")]
        [global::Xunit.TraitAttribute("Description", "View toolbar")]
        [global::Xunit.TraitAttribute("Category", "screenshot:toolbar")]
        public async global::System.Threading.Tasks.Task ViewToolbar()
        {
            string[] tagsOfScenario = new string[] {
                    "screenshot:toolbar"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View toolbar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
    await testRunner.WhenAsync("I navigate to the designer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
    await testRunner.ThenAsync("the toolbar should show save, run, validate, and settings buttons", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await WorkflowDesignerFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await WorkflowDesignerFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
