// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace WorkflowFramework.Dashboard.UITests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "UI")]
    public partial class WorkflowDesignerFeature : object, global::Xunit.IClassFixture<WorkflowDesignerFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "UI"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Workflow Designer", "  As a user I can visually design workflows using the drag-and-drop designer", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "WorkflowDesigner.feature"
#line hidden
        
        public WorkflowDesignerFeature(WorkflowDesignerFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/WorkflowDesigner.feature", "@UI\r\nFeature: Workflow Designer\r\n  As a user I can visually design workflows usin" +
                    "g the drag-and-drop designer\r\n\r\n  @screenshot:designer-overview\r\n  Scenario: Vie" +
                    "w empty designer on launch\r\n    Given the dashboard is running\r\n    When I navig" +
                    "ate to the designer\r\n    Then I should see the step palette on the left\r\n    And" +
                    " I should see an empty canvas\r\n    And I should see the properties panel on the " +
                    "right\r\n\r\n  @screenshot:step-palette\r\n  Scenario: Search step palette\r\n    Given " +
                    "the dashboard is running\r\n    When I navigate to the designer\r\n    And I type \"c" +
                    "onditional\" in the step search\r\n    Then I should see filtered steps containing " +
                    "\"conditional\"\r\n\r\n  @screenshot:properties-panel\r\n  Scenario: Select a node and v" +
                    "iew properties\r\n    Given the dashboard is running\r\n    And I have a workflow wi" +
                    "th an action step\r\n    When I click on the action step node\r\n    Then the proper" +
                    "ties panel should show the step configuration\r\n\r\n  Scenario: SubWorkflow step sh" +
                    "ows saved workflow suggestions\r\n    Given the dashboard is running\r\n    And I ha" +
                    "ve a workflow with a SubWorkflow step\r\n    When I select the SubWorkflow step\r\n " +
                    "   Then the properties panel should show saved workflow suggestions including \"C" +
                    "hild Flow\"\r\n    When I choose saved workflow \"Child Flow\"\r\n    Then the SubWorkf" +
                    "low reference should be \"Child Flow\"\r\n\r\n  @screenshot:toolbar\r\n  Scenario: View " +
                    "toolbar\r\n    Given the dashboard is running\r\n    When I navigate to the designer" +
                    "\r\n    Then the toolbar should show save, run, validate, and settings buttons\r\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/WorkflowDesigner.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(2, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), "@UI", "5077795886aa815999c714bbac21d117")}), "en", "Feature", "Workflow Designer", "  As a user I can visually design workflows using the drag-and-drop designer", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(5, new System.Nullable<long>(3)), "@screenshot:designer-overview", "86301e5a71900f5286a466cefe5f0cad")}), "Scenario", "View empty designer on launch", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "bfb2e2a5f3a4985298e293504aa916b2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I navigate to the designer", null, null, "c944185f85521851a0111d5d7ef298b4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see the step palette on the left", null, null, "4e554c9b6e37685bbfcbb67c523aa99b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I should see an empty canvas", null, null, "8bfcbec6ab15dc5fb53f5ca62832dad1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I should see the properties panel on the right", null, null, "f041f8ff9fe3db5a9d608abf9313f3cb")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "f734b9708789ac53b825740d69076aee")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(3)), "@screenshot:step-palette", "1ca4b7a55237ae54917e070670cec299")}), "Scenario", "Search step palette", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "153926eab3b6a85b9fabb62c7a40840f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I navigate to the designer", null, null, "ff2a7898adc8f05c97190acc0415e40e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I type \"conditional\" in the step search", null, null, "181112cbb9a13150962cd9ce530d9efb"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see filtered steps containing \"conditional\"", null, null, "06e9d466cd62255baa9be9441ad3ad49")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "4e8fa8d0ace62e57873a97a378c1b796")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(3)), "@screenshot:properties-panel", "cc5a026595eaad57b43884e59a18cb5c")}), "Scenario", "Select a node and view properties", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "d4925314f3dfe75c82b9593a7eb05973"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I have a workflow with an action step", null, null, "799f3356cb984c58b1932c3b89093279"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I click on the action step node", null, null, "8bc3434059dfb451acaa031adc239536"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the properties panel should show the step configuration", null, null, "41b7f57a935ae75ab3eab36a7f302282")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "255b4e2cfbb2335c8f07b84290cf9ef9")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "SubWorkflow step shows saved workflow suggestions", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "0a0b84cc33092d599dfdee7b3ada4ad0"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I have a workflow with a SubWorkflow step", null, null, "4c70be0bfb92ef598f42cc7c2ddad7ed"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I select the SubWorkflow step", null, null, "1833bf9553841f55af7dd82ec001ef4e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the properties panel should show saved workflow suggestions including \"Child Flow" +
                                                            "\"", null, null, "d9e7d8a53315b95e8cf6b1029a975434"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I choose saved workflow \"Child Flow\"", null, null, "3ede92de8c3f2658959d7ce0b5041075"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the SubWorkflow reference should be \"Child Flow\"", null, null, "02b9101ca6c3ba5297db7378d85209fe")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e129b1a85b859c5e81343525218f0325")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(3)), "@screenshot:toolbar", "1c151db2e7dc3c59ba53247790dd45d9")}), "Scenario", "View toolbar", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "b6895791d0fe4a5da769ad3954accbb5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I navigate to the designer", null, null, "01c3739309bc435d8f167a017cb10336"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the toolbar should show save, run, validate, and settings buttons", null, null, "78ade72c7a1d6251b0f5e6efdc960bb8")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "70bb9893ba216559a27ba0b5dee71d57"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("03ddad326dab2a5181da01e1e97dc8cf", "Features/WorkflowDesigner.feature", "View empty designer on launch", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bfb2e2a5f3a4985298e293504aa916b2"}), "4b181d993827a95ba244c56eb07ccdbd", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c944185f85521851a0111d5d7ef298b4"}), "02a5d3669cb879529e9f9ac889aedf32", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I navigate to the designer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4e554c9b6e37685bbfcbb67c523aa99b"}), "21820eccd5636959bb6728f97dd6608b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see the step palette on the left"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8bfcbec6ab15dc5fb53f5ca62832dad1"}), "b94da4127ed467518c235a1dddf9689b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see an empty canvas"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f041f8ff9fe3db5a9d608abf9313f3cb"}), "f12088596c22f157a93e9edea7391a87", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see the properties panel on the right")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "5077795886aa815999c714bbac21d117"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@screenshot:designer-overview", "86301e5a71900f5286a466cefe5f0cad")}), new System.Collections.Generic.List<string>(new string[] {
                                        "f734b9708789ac53b825740d69076aee"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("6ac818c315e24f5c9bc2e26428794944", "Features/WorkflowDesigner.feature", "Search step palette", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "153926eab3b6a85b9fabb62c7a40840f"}), "64440775282d9d5aac86bd79788e90d2", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ff2a7898adc8f05c97190acc0415e40e"}), "518bf60d3a00af53aa93bccda0005e0b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I navigate to the designer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "181112cbb9a13150962cd9ce530d9efb"}), "2c5ce00e4597195fa2ce78d39bc696f8", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I type \"conditional\" in the step search"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "06e9d466cd62255baa9be9441ad3ad49"}), "847481c28452605a818aae573bae7ed3", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see filtered steps containing \"conditional\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "5077795886aa815999c714bbac21d117"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@screenshot:step-palette", "1ca4b7a55237ae54917e070670cec299")}), new System.Collections.Generic.List<string>(new string[] {
                                        "4e8fa8d0ace62e57873a97a378c1b796"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("ea5a6c3be15fd351b20809e6a7a98c87", "Features/WorkflowDesigner.feature", "Select a node and view properties", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d4925314f3dfe75c82b9593a7eb05973"}), "c781966b4f9d2653bc14577b3e54b4ab", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "799f3356cb984c58b1932c3b89093279"}), "c7abb84d82c5c950b61554c835882c28", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I have a workflow with an action step"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8bc3434059dfb451acaa031adc239536"}), "71316ce5bb6e7c50af863efb8c700a28", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I click on the action step node"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "41b7f57a935ae75ab3eab36a7f302282"}), "45cf814f8318b354954a6f8d38977fad", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the properties panel should show the step configuration")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "5077795886aa815999c714bbac21d117"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@screenshot:properties-panel", "cc5a026595eaad57b43884e59a18cb5c")}), new System.Collections.Generic.List<string>(new string[] {
                                        "255b4e2cfbb2335c8f07b84290cf9ef9"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("d0ee74788f9fb25781ff15536c52cfe8", "Features/WorkflowDesigner.feature", "SubWorkflow step shows saved workflow suggestions", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0a0b84cc33092d599dfdee7b3ada4ad0"}), "95da292353b648598a70384878d75ad9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4c70be0bfb92ef598f42cc7c2ddad7ed"}), "f064eabc2e4fd2529b7fb94df82ca20f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I have a workflow with a SubWorkflow step"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1833bf9553841f55af7dd82ec001ef4e"}), "644ea6ec348ac153ab058b567ba1840f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I select the SubWorkflow step"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d9e7d8a53315b95e8cf6b1029a975434"}), "3fe64fc703beb057ba640fa3716beae3", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the properties panel should show saved workflow suggestions including \"Child Flow" +
                                                "\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3ede92de8c3f2658959d7ce0b5041075"}), "bb71b3430e3e3f578d58739d5900982b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I choose saved workflow \"Child Flow\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "02b9101ca6c3ba5297db7378d85209fe"}), "17ebdd9bc9b47658b7bbc14bcdaf5bd5", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the SubWorkflow reference should be \"Child Flow\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "5077795886aa815999c714bbac21d117")}), new System.Collections.Generic.List<string>(new string[] {
                                        "e129b1a85b859c5e81343525218f0325"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("ead7fb3a365807559894e28b931a479f", "Features/WorkflowDesigner.feature", "View toolbar", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b6895791d0fe4a5da769ad3954accbb5"}), "77c2fe0b70e34750afb5a005ff352877", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "01c3739309bc435d8f167a017cb10336"}), "5d5f17df40cc5a59834862ff2c72f3ec", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I navigate to the designer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "78ade72c7a1d6251b0f5e6efdc960bb8"}), "55cb2f3f1968b05f9e144ba7e9272092", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the toolbar should show save, run, validate, and settings buttons")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "5077795886aa815999c714bbac21d117"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@screenshot:toolbar", "1c151db2e7dc3c59ba53247790dd45d9")}), new System.Collections.Generic.List<string>(new string[] {
                                        "70bb9893ba216559a27ba0b5dee71d57"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(WorkflowDesignerFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(WorkflowDesignerFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(WorkflowDesignerFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="View empty designer on launch")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Designer")]
        [global::Xunit.TraitAttribute("Description", "View empty designer on launch")]
        [global::Xunit.TraitAttribute("Category", "screenshot:designer-overview")]
        public async global::System.Threading.Tasks.Task ViewEmptyDesignerOnLaunch()
        {
            string[] tagsOfScenario = new string[] {
                    "screenshot:designer-overview"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View empty designer on launch", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.WhenAsync("I navigate to the designer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.ThenAsync("I should see the step palette on the left", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 10
    await testRunner.AndAsync("I should see an empty canvas", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.AndAsync("I should see the properties panel on the right", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Search step palette")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Designer")]
        [global::Xunit.TraitAttribute("Description", "Search step palette")]
        [global::Xunit.TraitAttribute("Category", "screenshot:step-palette")]
        public async global::System.Threading.Tasks.Task SearchStepPalette()
        {
            string[] tagsOfScenario = new string[] {
                    "screenshot:step-palette"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Search step palette", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
    await testRunner.WhenAsync("I navigate to the designer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
    await testRunner.AndAsync("I type \"conditional\" in the step search", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.ThenAsync("I should see filtered steps containing \"conditional\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Select a node and view properties")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Designer")]
        [global::Xunit.TraitAttribute("Description", "Select a node and view properties")]
        [global::Xunit.TraitAttribute("Category", "screenshot:properties-panel")]
        public async global::System.Threading.Tasks.Task SelectANodeAndViewProperties()
        {
            string[] tagsOfScenario = new string[] {
                    "screenshot:properties-panel"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Select a node and view properties", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
    await testRunner.AndAsync("I have a workflow with an action step", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.WhenAsync("I click on the action step node", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("the properties panel should show the step configuration", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="SubWorkflow step shows saved workflow suggestions")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Designer")]
        [global::Xunit.TraitAttribute("Description", "SubWorkflow step shows saved workflow suggestions")]
        public async global::System.Threading.Tasks.Task SubWorkflowStepShowsSavedWorkflowSuggestions()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("SubWorkflow step shows saved workflow suggestions", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 29
    await testRunner.AndAsync("I have a workflow with a SubWorkflow step", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
    await testRunner.WhenAsync("I select the SubWorkflow step", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
    await testRunner.ThenAsync("the properties panel should show saved workflow suggestions including \"Child Flow" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 32
    await testRunner.WhenAsync("I choose saved workflow \"Child Flow\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
    await testRunner.ThenAsync("the SubWorkflow reference should be \"Child Flow\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="View toolbar")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Designer")]
        [global::Xunit.TraitAttribute("Description", "View toolbar")]
        [global::Xunit.TraitAttribute("Category", "screenshot:toolbar")]
        public async global::System.Threading.Tasks.Task ViewToolbar()
        {
            string[] tagsOfScenario = new string[] {
                    "screenshot:toolbar"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View toolbar", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
    await testRunner.WhenAsync("I navigate to the designer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
    await testRunner.ThenAsync("the toolbar should show save, run, validate, and settings buttons", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await WorkflowDesignerFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await WorkflowDesignerFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
