// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace WorkflowFramework.Dashboard.UITests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "UI")]
    public partial class WorkflowExecutionDeepFeature : object, global::Xunit.IClassFixture<WorkflowExecutionDeepFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "UI"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "Features", "Workflow Execution Deep", "  Workflows execute with real step processing and live progress", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "WorkflowExecution.feature"
#line hidden
        
        public WorkflowExecutionDeepFeature(WorkflowExecutionDeepFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/WorkflowExecution.feature", "@UI\nFeature: Workflow Execution Deep\n  Workflows execute with real step processin" +
                    "g and live progress\n\n  Scenario: Run Hello World workflow end-to-end\n    Given t" +
                    "he dashboard is running\n    And I open the \"Hello World\" sample workflow\n    Whe" +
                    "n I save and run the workflow\n    Then the execution panel should show \"Running\"" +
                    "\n    And I should see step progress updates\n    And the run should complete with" +
                    " status \"Completed\"\n\n  @local-ollama @screenshot:ollama-local-run\n  Scenario: Ru" +
                    "n local Ollama workflow end-to-end\n    Given the dashboard is running\n    And I " +
                    "am on the settings page\n    When I set the Ollama URL to \"http://localhost:11434" +
                    "\"\n    And I select \"ollama\" as the default provider\n    Then the model dropdown " +
                    "should be populated\n    When I select a model\n    And I click Save Settings\n    " +
                    "Then I should see a success toast\n    When I reload the settings page\n    Then \"" +
                    "ollama\" should be selected as the default provider\n    When I navigate to the de" +
                    "signer\n    And I open the \"Local Ollama Smoke Test\" sample workflow\n    And I sa" +
                    "ve and run the workflow\n    Then the execution panel should show \"Running\"\n    A" +
                    "nd I should see step progress updates\n    And the run should complete with statu" +
                    "s \"Completed\"\n    And the latest run for the current workflow should include an " +
                    "AI response from step \"GenerateLocalReply\"\n\n  Scenario: Run HTTP workflow makes " +
                    "real requests\n    Given the dashboard is running\n    And I open the \"HTTP API Or" +
                    "chestration\" sample workflow\n    When I save and run the workflow\n    Then I sho" +
                    "uld see step \"FetchUserData\" complete\n    And I should see step \"FetchUserPosts\"" +
                    " complete\n    And the run should complete with status \"Completed\"\n\n  Scenario: C" +
                    "ancel a running workflow\n    Given the dashboard is running\n    And I have a wor" +
                    "kflow with a Delay step of 30000ms\n    When I save and run the workflow\n    And " +
                    "the workflow is running\n    When I cancel the run\n    Then the run should show s" +
                    "tatus \"Cancelled\"\n\n  Scenario: Failed step shows error in output\n    Given the d" +
                    "ashboard is running\n    And I have a workflow with an HttpStep pointing to an in" +
                    "valid URL\n    When I save and run the workflow\n    Then I should see a step fail" +
                    "ure in the output panel\n    And the run should complete with status \"Failed\"\n\n  " +
                    "Scenario: View run in history after completion\n    Given the dashboard is runnin" +
                    "g\n    And I open the \"Hello World\" sample workflow\n    When I save and run the w" +
                    "orkflow\n    And the run completes\n    Then the run should appear in the runs lis" +
                    "t via API\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/WorkflowExecution.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(2, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), "@UI", "61e849543b48455e911e66807f650fca")}), "en", "Feature", "Workflow Execution Deep", "  Workflows execute with real step processing and live progress", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(5, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Run Hello World workflow end-to-end", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "c717ab0adbd42551acdc167c02074261"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I open the \"Hello World\" sample workflow", null, null, "74c3e5965d79aa5ea1c2c8b59cc16098"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I save and run the workflow", null, null, "f5040d5a4620f05785f23103bb6916e0"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the execution panel should show \"Running\"", null, null, "e23500056b242654923d37af377288df"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I should see step progress updates", null, null, "ee51452a2c58f75c8b422098e096b398"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the run should complete with status \"Completed\"", null, null, "6fdf0f9e456fcb5d8a634da0e116309c")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "2d8561d05a4aa65983fa9e4d774a503f")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[] {
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(3)), "@local-ollama", "5b14c39fd679ca51bd3b23769afeda9d"),
                                                    new global::Io.Cucumber.Messages.Types.Tag(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(17)), "@screenshot:ollama-local-run", "859f192ce012f65aa1bea381a3079f5d")}), "Scenario", "Run local Ollama workflow end-to-end", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "a22ef8b3f91a045ca6b0551716491e30"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I am on the settings page", null, null, "83811f979f941b55b8a6bc9d49fba52c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I set the Ollama URL to \"http://localhost:11434\"", null, null, "ae6aae71e6149f5f9a69493f69cb121c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I select \"ollama\" as the default provider", null, null, "7dd6bd8501da3251bb125abd4463fe28"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the model dropdown should be populated", null, null, "3e6babb62913a35b8cef586002811493"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I select a model", null, null, "c79fd8534135ad5fa9e6df75f58bedaa"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I click Save Settings", null, null, "f13365b3089baa578a829e4b6ff350ee"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see a success toast", null, null, "c49932fb66511a5194223259c8d89514"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I reload the settings page", null, null, "a18af31468f7eb5ead6963faa7cdb892"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "\"ollama\" should be selected as the default provider", null, null, "74fee0eeb6ddb951a4ae93b50646a7b0"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I navigate to the designer", null, null, "90c93e7ec1ab9b599c08e26ec530dd12"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I open the \"Local Ollama Smoke Test\" sample workflow", null, null, "a960c5145196c05db78600ddca59cf32"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I save and run the workflow", null, null, "abf62f1b9e73415ab8ad977da440bd6c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the execution panel should show \"Running\"", null, null, "498234c029cde3509dfaff100bb88123"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I should see step progress updates", null, null, "c7504289fe7ce85bafbd97e649cd6a94"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the run should complete with status \"Completed\"", null, null, "27929f78ebf87d50b73296bb308a16ea"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the latest run for the current workflow should include an AI response from step \"" +
                                                            "GenerateLocalReply\"", null, null, "c3af9ea10b012d548e92e2906aa77e12")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "f594022c8886a957af95a4f8b4e90254")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(33, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Run HTTP workflow makes real requests", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(34, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "c4f7393d14d4845486e85933eb7934ab"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(35, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I open the \"HTTP API Orchestration\" sample workflow", null, null, "a5cd895b7e028659a33bf25e01715ff5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(36, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I save and run the workflow", null, null, "f24f3728cc540150a169a66682525b69"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(37, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see step \"FetchUserData\" complete", null, null, "c61dbebf0696b05eb0d53afda50e70c5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(38, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I should see step \"FetchUserPosts\" complete", null, null, "7e669c0d8fa4a9599f76dc3fbbac5f36"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(39, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the run should complete with status \"Completed\"", null, null, "303bd180b8956950ade853d0c08959ed")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "2085c348c9692e59861445659171908c")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(41, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Cancel a running workflow", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(42, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "f2bd2e5a7c3715539986477dbc2bc679"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(43, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I have a workflow with a Delay step of 30000ms", null, null, "a6fb14c215e5bc549600fd7031ca8726"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(44, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I save and run the workflow", null, null, "3848f5448835685da04928bef9fc3ede"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(45, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the workflow is running", null, null, "8db8c55eb1485a5abc23346ed1476fe3"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(46, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I cancel the run", null, null, "4854d5683d3e855599d464ab4e9edb83"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(47, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the run should show status \"Cancelled\"", null, null, "ef1b25f3d2f0945eb3441bf4e8052d90")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "a0f57055a6b694599ec4ec5559157993")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(49, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Failed step shows error in output", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(50, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "4e1650aa1a59465e9c7db7853332594f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(51, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I have a workflow with an HttpStep pointing to an invalid URL", null, null, "5c0fb54238b4e45f9f745e3831b937a4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(52, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I save and run the workflow", null, null, "ff911e6dc8aa3250861c88ef2272ea80"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(53, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "I should see a step failure in the output panel", null, null, "d8b4799cbcfcea56a4a43b177ce278fd"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(54, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the run should complete with status \"Failed\"", null, null, "428e6338d5ebfa52b4b4376f437f7710")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "ac6ec1317decf45a939f47736a0ddef7")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(56, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "View run in history after completion", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(57, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the dashboard is running", null, null, "f7b95681ee079e5bb8e5d1ed01100d23"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(58, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "I open the \"Hello World\" sample workflow", null, null, "bbcdc110d23ef35887511a21c5eec233"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(59, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "I save and run the workflow", null, null, "925d88fa50f528549a3100a048fc5250"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(60, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the run completes", null, null, "f5be5b32da41545a9b7906f063dae87e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(61, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the run should appear in the runs list via API", null, null, "a850b3afffc2fa5aaf93bde871f21262")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "1aecd7288d508f5a96e92e49bab397c9"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("92991bcc77004d58864721840efbc2b1", "Features/WorkflowExecution.feature", "Run Hello World workflow end-to-end", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c717ab0adbd42551acdc167c02074261"}), "38b4acdf05d8d35dac8726062fca2cd9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "74c3e5965d79aa5ea1c2c8b59cc16098"}), "5d28e64309032e50a34c87cb3236362c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I open the \"Hello World\" sample workflow"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f5040d5a4620f05785f23103bb6916e0"}), "57bee731c24f395cadc80226c7bdf211", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I save and run the workflow"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e23500056b242654923d37af377288df"}), "dfaee495ebc32759a8a901b3ee45d910", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the execution panel should show \"Running\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ee51452a2c58f75c8b422098e096b398"}), "d7b4646db34706559ff59f6401d16535", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see step progress updates"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6fdf0f9e456fcb5d8a634da0e116309c"}), "487657b335f9f75598db8355f872b46a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the run should complete with status \"Completed\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "61e849543b48455e911e66807f650fca")}), new System.Collections.Generic.List<string>(new string[] {
                                        "2d8561d05a4aa65983fa9e4d774a503f"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("ce60e2840d9a4d59a8d4848be7151179", "Features/WorkflowExecution.feature", "Run local Ollama workflow end-to-end", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a22ef8b3f91a045ca6b0551716491e30"}), "5e7a91a59cbbfb5fa3f4d56c548ff6b1", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "83811f979f941b55b8a6bc9d49fba52c"}), "c63ea467b24cc559a8aabea5d7923f04", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I am on the settings page"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ae6aae71e6149f5f9a69493f69cb121c"}), "c99dab944ffd9a5e8cbaa2fd54a9b92c", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I set the Ollama URL to \"http://localhost:11434\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7dd6bd8501da3251bb125abd4463fe28"}), "f4ddece13691fc5bb301db66acb7afb0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I select \"ollama\" as the default provider"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3e6babb62913a35b8cef586002811493"}), "871a6efc9a1bb85fa190306635005d1d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the model dropdown should be populated"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c79fd8534135ad5fa9e6df75f58bedaa"}), "605cf37d808a6358b297449bf5211ba0", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I select a model"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f13365b3089baa578a829e4b6ff350ee"}), "c762d129421d8e5b9a4ccbc2acee636b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I click Save Settings"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c49932fb66511a5194223259c8d89514"}), "e2bacc8f04cb835ba536b9c363a49b1a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see a success toast"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a18af31468f7eb5ead6963faa7cdb892"}), "e5c757f773eb5a5d9e2dab8d229f80ed", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I reload the settings page"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "74fee0eeb6ddb951a4ae93b50646a7b0"}), "ee0a7912ee7a605b8efb78ff8a138e68", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "\"ollama\" should be selected as the default provider"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "90c93e7ec1ab9b599c08e26ec530dd12"}), "b4c66da2f5fdb459a09c6d633e014215", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I navigate to the designer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a960c5145196c05db78600ddca59cf32"}), "d87df9a72ee0eb5db41f2d867922b49e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I open the \"Local Ollama Smoke Test\" sample workflow"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "abf62f1b9e73415ab8ad977da440bd6c"}), "ce0acc8c4a925853a9f5192b2069f2b3", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I save and run the workflow"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "498234c029cde3509dfaff100bb88123"}), "159c03926a85775fb7d1c0ca0a5f3e83", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the execution panel should show \"Running\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c7504289fe7ce85bafbd97e649cd6a94"}), "f0cc9e3a82b66d5781577a0a17d5fd41", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see step progress updates"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "27929f78ebf87d50b73296bb308a16ea"}), "db332f579a6344568ffa885e3063419d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the run should complete with status \"Completed\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c3af9ea10b012d548e92e2906aa77e12"}), "3e5bbfe6d3bfee5486267e0572341b2b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the latest run for the current workflow should include an AI response from step \"" +
                                                "GenerateLocalReply\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "61e849543b48455e911e66807f650fca"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@local-ollama", "5b14c39fd679ca51bd3b23769afeda9d"),
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@screenshot:ollama-local-run", "859f192ce012f65aa1bea381a3079f5d")}), new System.Collections.Generic.List<string>(new string[] {
                                        "f594022c8886a957af95a4f8b4e90254"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("8e87f07e66eeb558901ae1b015e465e7", "Features/WorkflowExecution.feature", "Run HTTP workflow makes real requests", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c4f7393d14d4845486e85933eb7934ab"}), "44fb802bb8e6da5cb9480b6f0c9df7d7", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a5cd895b7e028659a33bf25e01715ff5"}), "6b0a8167b7c41a528aae82a0397d0985", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I open the \"HTTP API Orchestration\" sample workflow"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f24f3728cc540150a169a66682525b69"}), "203cdbd391516e559777b3359ac95e0d", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I save and run the workflow"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c61dbebf0696b05eb0d53afda50e70c5"}), "34784ffe53f88556b5cd1ff1d326b882", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see step \"FetchUserData\" complete"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7e669c0d8fa4a9599f76dc3fbbac5f36"}), "12869517aa03cf54bd79545a178dc99e", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see step \"FetchUserPosts\" complete"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "303bd180b8956950ade853d0c08959ed"}), "7b8e54e10bad735a900cbac6f46f055a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the run should complete with status \"Completed\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "61e849543b48455e911e66807f650fca")}), new System.Collections.Generic.List<string>(new string[] {
                                        "2085c348c9692e59861445659171908c"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("97a27a50234f9855aeb802b124f10c3e", "Features/WorkflowExecution.feature", "Cancel a running workflow", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f2bd2e5a7c3715539986477dbc2bc679"}), "0e8746cac9642c5293120896633da7ea", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a6fb14c215e5bc549600fd7031ca8726"}), "ec2f94583a7c3955bf14df29e16365f8", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I have a workflow with a Delay step of 30000ms"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3848f5448835685da04928bef9fc3ede"}), "a2109c2bdb59f1529532b5a60d33e5f2", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I save and run the workflow"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8db8c55eb1485a5abc23346ed1476fe3"}), "274fd4f2b459c05cb03198cf6f23503b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the workflow is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4854d5683d3e855599d464ab4e9edb83"}), "301097d3919b4f5c9378efc0fff0ac2b", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I cancel the run"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ef1b25f3d2f0945eb3441bf4e8052d90"}), "b4a85142b2374d5abdbefd41924f0833", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the run should show status \"Cancelled\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "61e849543b48455e911e66807f650fca")}), new System.Collections.Generic.List<string>(new string[] {
                                        "a0f57055a6b694599ec4ec5559157993"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("bb47a2c3198e6d59a28a6e4342eaec1a", "Features/WorkflowExecution.feature", "Failed step shows error in output", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4e1650aa1a59465e9c7db7853332594f"}), "16664df917f6235b94182f5b2bef70ab", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "5c0fb54238b4e45f9f745e3831b937a4"}), "26a71350d2e6cc5394128c58bfda5971", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I have a workflow with an HttpStep pointing to an invalid URL"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ff911e6dc8aa3250861c88ef2272ea80"}), "06dc20254be1a75485c18b2676879b07", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I save and run the workflow"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d8b4799cbcfcea56a4a43b177ce278fd"}), "4a053a682ac9be5eb04bee5504b934c8", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "I should see a step failure in the output panel"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "428e6338d5ebfa52b4b4376f437f7710"}), "5e119657e58d8e58a0fd6a15c51cf3f2", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the run should complete with status \"Failed\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "61e849543b48455e911e66807f650fca")}), new System.Collections.Generic.List<string>(new string[] {
                                        "ac6ec1317decf45a939f47736a0ddef7"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("76a9d0d8c8af5b52a6cc6e40f6703acc", "Features/WorkflowExecution.feature", "View run in history after completion", "en", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f7b95681ee079e5bb8e5d1ed01100d23"}), "bb691fdcbea51751b84edabe0ecdfb34", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the dashboard is running"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bbcdc110d23ef35887511a21c5eec233"}), "00c6afc26eab465ab690b9294fd8f5be", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "I open the \"Hello World\" sample workflow"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "925d88fa50f528549a3100a048fc5250"}), "636607e66c62fc5399180637033fb4c6", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "I save and run the workflow"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f5be5b32da41545a9b7906f063dae87e"}), "816e2e9b92b1cd529f30b2201f2b136c", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the run completes"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a850b3afffc2fa5aaf93bde871f21262"}), "b8acc7e9ee549959b26a3f9d2f48ae91", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the run should appear in the runs list via API")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[] {
                                        new global::Io.Cucumber.Messages.Types.PickleTag("@UI", "61e849543b48455e911e66807f650fca")}), new System.Collections.Generic.List<string>(new string[] {
                                        "1aecd7288d508f5a96e92e49bab397c9"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(WorkflowExecutionDeepFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(WorkflowExecutionDeepFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(WorkflowExecutionDeepFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Run Hello World workflow end-to-end")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Execution Deep")]
        [global::Xunit.TraitAttribute("Description", "Run Hello World workflow end-to-end")]
        public async global::System.Threading.Tasks.Task RunHelloWorldWorkflowEnd_To_End()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Run Hello World workflow end-to-end", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.AndAsync("I open the \"Hello World\" sample workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.WhenAsync("I save and run the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.ThenAsync("the execution panel should show \"Running\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 10
    await testRunner.AndAsync("I should see step progress updates", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.AndAsync("the run should complete with status \"Completed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Run local Ollama workflow end-to-end")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Execution Deep")]
        [global::Xunit.TraitAttribute("Description", "Run local Ollama workflow end-to-end")]
        [global::Xunit.TraitAttribute("Category", "local-ollama")]
        [global::Xunit.TraitAttribute("Category", "screenshot:ollama-local-run")]
        public async global::System.Threading.Tasks.Task RunLocalOllamaWorkflowEnd_To_End()
        {
            string[] tagsOfScenario = new string[] {
                    "local-ollama",
                    "screenshot:ollama-local-run"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Run local Ollama workflow end-to-end", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
    await testRunner.AndAsync("I am on the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.WhenAsync("I set the Ollama URL to \"http://localhost:11434\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
    await testRunner.AndAsync("I select \"ollama\" as the default provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.ThenAsync("the model dropdown should be populated", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
    await testRunner.WhenAsync("I select a model", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.AndAsync("I click Save Settings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.ThenAsync("I should see a success toast", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
    await testRunner.WhenAsync("I reload the settings page", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
    await testRunner.ThenAsync("\"ollama\" should be selected as the default provider", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
    await testRunner.WhenAsync("I navigate to the designer", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.AndAsync("I open the \"Local Ollama Smoke Test\" sample workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.AndAsync("I save and run the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
    await testRunner.ThenAsync("the execution panel should show \"Running\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
    await testRunner.AndAsync("I should see step progress updates", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
    await testRunner.AndAsync("the run should complete with status \"Completed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.AndAsync("the latest run for the current workflow should include an AI response from step \"" +
                        "GenerateLocalReply\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Run HTTP workflow makes real requests")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Execution Deep")]
        [global::Xunit.TraitAttribute("Description", "Run HTTP workflow makes real requests")]
        public async global::System.Threading.Tasks.Task RunHTTPWorkflowMakesRealRequests()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Run HTTP workflow makes real requests", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
    await testRunner.AndAsync("I open the \"HTTP API Orchestration\" sample workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.WhenAsync("I save and run the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
    await testRunner.ThenAsync("I should see step \"FetchUserData\" complete", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 38
    await testRunner.AndAsync("I should see step \"FetchUserPosts\" complete", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
    await testRunner.AndAsync("the run should complete with status \"Completed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cancel a running workflow")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Execution Deep")]
        [global::Xunit.TraitAttribute("Description", "Cancel a running workflow")]
        public async global::System.Threading.Tasks.Task CancelARunningWorkflow()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cancel a running workflow", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 41
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 42
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 43
    await testRunner.AndAsync("I have a workflow with a Delay step of 30000ms", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
    await testRunner.WhenAsync("I save and run the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
    await testRunner.AndAsync("the workflow is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
    await testRunner.WhenAsync("I cancel the run", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
    await testRunner.ThenAsync("the run should show status \"Cancelled\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Failed step shows error in output")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Execution Deep")]
        [global::Xunit.TraitAttribute("Description", "Failed step shows error in output")]
        public async global::System.Threading.Tasks.Task FailedStepShowsErrorInOutput()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Failed step shows error in output", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 49
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 50
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
    await testRunner.AndAsync("I have a workflow with an HttpStep pointing to an invalid URL", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
    await testRunner.WhenAsync("I save and run the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
    await testRunner.ThenAsync("I should see a step failure in the output panel", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
    await testRunner.AndAsync("the run should complete with status \"Failed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="View run in history after completion")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Workflow Execution Deep")]
        [global::Xunit.TraitAttribute("Description", "View run in history after completion")]
        public async global::System.Threading.Tasks.Task ViewRunInHistoryAfterCompletion()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("View run in history after completion", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 56
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 57
    await testRunner.GivenAsync("the dashboard is running", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 58
    await testRunner.AndAsync("I open the \"Hello World\" sample workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.WhenAsync("I save and run the workflow", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
    await testRunner.AndAsync("the run completes", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.ThenAsync("the run should appear in the runs list via API", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await WorkflowExecutionDeepFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await WorkflowExecutionDeepFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
