using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace WorkflowFramework.Generators;

/// <summary>
/// Source generator that discovers IStep implementations and generates
/// a registration extension method for DI.
/// </summary>
[Generator]
public sealed class StepRegistrationGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var stepTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds &&
                    cds.BaseList != null &&
                    !cds.Modifiers.Any(Microsoft.CodeAnalysis.CSharp.SyntaxKind.AbstractKeyword),
                transform: static (ctx, ct) =>
                {
                    var classDecl = (ClassDeclarationSyntax)ctx.Node;
                    var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl, ct) as INamedTypeSymbol;
                    if (symbol is null) return null;

                    foreach (var iface in symbol.AllInterfaces)
                    {
                        if (iface.Name == "IStep" && iface.ContainingNamespace.ToDisplayString() == "WorkflowFramework")
                            return symbol;
                        if (iface.IsGenericType && iface.OriginalDefinition.Name == "IStep" &&
                            iface.ContainingNamespace.ToDisplayString() == "WorkflowFramework")
                            return symbol;
                    }
                    return null;
                })
            .Where(static s => s is not null)
            .Collect();

        context.RegisterSourceOutput(stepTypes, static (ctx, types) =>
        {
            if (types.IsDefaultOrEmpty) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("namespace WorkflowFramework.Generated;");
            sb.AppendLine();
            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Auto-generated step registration extensions.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"WorkflowFramework.Generators\", \"1.0.0\")]");
            sb.AppendLine("public static class StepRegistrations");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Gets all discovered step types.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static global::System.Type[] GetAllStepTypes() => new global::System.Type[]");
            sb.AppendLine("    {");

            foreach (var type in types)
            {
                if (type is null) continue;
                sb.AppendLine($"        typeof(global::{type.ToDisplayString()}),");
            }

            sb.AppendLine("    };");
            sb.AppendLine("}");

            ctx.AddSource("StepRegistrations.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }
}
