using TinyBDD;
using TinyBDD.Xunit;
using Xunit;
using Xunit.Abstractions;
using FluentAssertions;
using NSubstitute;
using WorkflowFramework.Tests.TinyBDD.Support;
using WorkflowFramework.Extensions.Integration.Transformation;
using PatternKit.Messaging;
using PatternKit.Messaging.Transformation;

namespace WorkflowFramework.Tests.TinyBDD.Integration.Transformation;

// Phase 3 — re-rooted on PatternKit IClaimCheckStore<object>.
//
// Behavioral change rationale:
//   - ClaimCheckStep now generates a deterministic Guid claim ID (N-format) and passes it
//     to IClaimCheckStore<object>.StoreAsync. Previously the store returned the ID.
//   - The ticket written to ClaimTicketKey is now the step-generated ID (not store-returned).
//   - ClaimRetrieveStep calls TryLoadAsync and throws if the stored payload is null/not found.
//   - The legacy WF IClaimCheckStore interface is now [Obsolete]; steps consume the PatternKit
//     typed interface directly. A LegacyClaimCheckStoreAdapter bridges old impls for one release.
// See .plan/patternkit-iteration-2.md §3.

[Feature("ClaimCheckStep & ClaimRetrieveStep — characterization (Phase G.5, updated Phase 3)")]
public class ClaimCheckStepScenarios : TinyBddTestBase
{
    public ClaimCheckStepScenarios(ITestOutputHelper output) : base(output) { }

    // ── ClaimCheckStep ──────────────────────────────────────────────────────

    [Scenario("ClaimCheckStep.Name returns 'ClaimCheck'"), Fact]
    public async Task ClaimCheckNameIsClaimCheck()
    {
        var store = Substitute.For<IClaimCheckStore<object>>();
        var sut = new ClaimCheckStep(store, _ => new object());

        await Given("ClaimCheckStep instance", () => sut)
            .Then("Name is 'ClaimCheck'", s =>
            {
                s.Name.Should().Be("ClaimCheck");
                return true;
            })
            .AssertPassed();
    }

    [Scenario("ClaimCheckStep null store throws ArgumentNullException"), Fact]
    public async Task ClaimCheckNullStoreThrows()
    {
        Exception? caught = null;
        try { _ = new ClaimCheckStep(null!, _ => new object()); }
        catch (ArgumentNullException ex) { caught = ex; }

        await Given("construction with null store", () => caught)
            .Then("ArgumentNullException is thrown", ex =>
            {
                ex.Should().NotBeNull().And.BeOfType<ArgumentNullException>();
                return true;
            })
            .AssertPassed();
    }

    [Scenario("ClaimCheckStep null payloadSelector throws ArgumentNullException"), Fact]
    public async Task ClaimCheckNullPayloadSelectorThrows()
    {
        var store = Substitute.For<IClaimCheckStore<object>>();
        Exception? caught = null;
        try { _ = new ClaimCheckStep(store, null!); }
        catch (ArgumentNullException ex) { caught = ex; }

        await Given("construction with null payloadSelector", () => caught)
            .Then("ArgumentNullException is thrown", ex =>
            {
                ex.Should().NotBeNull().And.BeOfType<ArgumentNullException>();
                return true;
            })
            .AssertPassed();
    }

    [Scenario("ClaimTicketKey constant has expected value"), Fact]
    public async Task ClaimTicketKeyHasExpectedValue()
    {
        await Given("ClaimCheckStep.ClaimTicketKey constant", () => ClaimCheckStep.ClaimTicketKey)
            .Then("value is '__ClaimTicket'", key =>
            {
                key.Should().Be("__ClaimTicket");
                return true;
            })
            .AssertPassed();
    }

    [Scenario("ExecuteAsync stores a non-null ticket string on context"), Fact]
    public async Task ExecuteStoresTicketOnContext()
    {
        // Behavioral change (Phase 3): claim ID is now generated by the step (Guid.NewGuid "N"),
        // not returned by the store. The ticket stored on context is the step-generated ID.
        var store = Substitute.For<IClaimCheckStore<object>>();
        store.StoreAsync(Arg.Any<string>(), Arg.Any<object>(), Arg.Any<MessageHeaders>(), Arg.Any<CancellationToken>())
             .Returns(ValueTask.CompletedTask);

        var ctx = new WorkflowContext();
        var sut = new ClaimCheckStep(store, _ => new { Data = "large-payload" });
        await sut.ExecuteAsync(ctx);

        await Given("context after claim check step", () => ctx)
            .Then("ClaimTicketKey holds a non-null, non-empty ticket string", c =>
            {
                var ticket = c.Properties[ClaimCheckStep.ClaimTicketKey] as string;
                ticket.Should().NotBeNullOrEmpty();
                return true;
            })
            .AssertPassed();
    }

    [Scenario("StoreAsync is called with the payload selected from context"), Fact]
    public async Task StoreAsyncReceivesSelectedPayload()
    {
        object? savedPayload = null;
        var store = Substitute.For<IClaimCheckStore<object>>();
        store.StoreAsync(
                Arg.Any<string>(),
                Arg.Do<object>(p => savedPayload = p),
                Arg.Any<MessageHeaders>(),
                Arg.Any<CancellationToken>())
             .Returns(ValueTask.CompletedTask);

        var payload = new { Value = 99 };
        var ctx = new WorkflowContext();
        ctx.Properties["payload"] = payload;
        var sut = new ClaimCheckStep(store, c => c.Properties["payload"]!);
        await sut.ExecuteAsync(ctx);

        await Given("payload passed to StoreAsync", () => savedPayload)
            .Then("it is the payload selected from context", p =>
            {
                p.Should().BeSameAs(payload);
                return true;
            })
            .AssertPassed();
    }

    [Scenario("StoreAsync is called with the context cancellation token"), Fact]
    public async Task StoreAsyncReceivesCancellationToken()
    {
        using var cts = new CancellationTokenSource();
        var capturedToken = CancellationToken.None;

        var store = Substitute.For<IClaimCheckStore<object>>();
        store.StoreAsync(
                Arg.Any<string>(),
                Arg.Any<object>(),
                Arg.Any<MessageHeaders>(),
                Arg.Do<CancellationToken>(t => capturedToken = t))
             .Returns(ValueTask.CompletedTask);

        var ctx = new WorkflowContext(cts.Token);
        var sut = new ClaimCheckStep(store, _ => "payload");
        await sut.ExecuteAsync(ctx);

        await Given("captured CancellationToken from StoreAsync", () => capturedToken)
            .Then("it equals the context's CancellationToken", token =>
            {
                token.Should().Be(cts.Token);
                return true;
            })
            .AssertPassed();
    }

    // ── ClaimRetrieveStep ───────────────────────────────────────────────────

    [Scenario("ClaimRetrieveStep.Name returns 'ClaimRetrieve'"), Fact]
    public async Task ClaimRetrieveNameIsClaimRetrieve()
    {
        var store = Substitute.For<IClaimCheckStore<object>>();
        var sut = new ClaimRetrieveStep(store);

        await Given("ClaimRetrieveStep instance", () => sut)
            .Then("Name is 'ClaimRetrieve'", s =>
            {
                s.Name.Should().Be("ClaimRetrieve");
                return true;
            })
            .AssertPassed();
    }

    [Scenario("ClaimRetrieveStep null store throws ArgumentNullException"), Fact]
    public async Task ClaimRetrieveNullStoreThrows()
    {
        Exception? caught = null;
        try { _ = new ClaimRetrieveStep(null!); }
        catch (ArgumentNullException ex) { caught = ex; }

        await Given("construction with null store", () => caught)
            .Then("ArgumentNullException is thrown", ex =>
            {
                ex.Should().NotBeNull().And.BeOfType<ArgumentNullException>();
                return true;
            })
            .AssertPassed();
    }

    [Scenario("ClaimRetrieveStep retrieves payload using ticket from context"), Fact]
    public async Task ClaimRetrieveUsesTicketFromContext()
    {
        var payload = new { Retrieved = true };
        var stored = new ClaimCheckStoredPayload<object>(payload, MessageHeaders.Empty);
        var store = Substitute.For<IClaimCheckStore<object>>();
        store.TryLoadAsync("ticket-abc", Arg.Any<CancellationToken>())
             .Returns(new ValueTask<ClaimCheckStoredPayload<object>?>(stored));

        var ctx = new WorkflowContext();
        ctx.Properties[ClaimCheckStep.ClaimTicketKey] = "ticket-abc";
        var sut = new ClaimRetrieveStep(store);
        await sut.ExecuteAsync(ctx);

        await Given("context after retrieve step", () => ctx)
            .Then("default result key holds the retrieved payload", c =>
            {
                c.Properties["__ClaimPayload"].Should().BeSameAs(payload);
                return true;
            })
            .AssertPassed();
    }

    [Scenario("ClaimRetrieveStep with custom resultKey stores payload under that key"), Fact]
    public async Task ClaimRetrieveCustomResultKeyUsed()
    {
        var payload = "the-payload";
        var stored = new ClaimCheckStoredPayload<object>(payload, MessageHeaders.Empty);
        var store = Substitute.For<IClaimCheckStore<object>>();
        store.TryLoadAsync(Arg.Any<string>(), Arg.Any<CancellationToken>())
             .Returns(new ValueTask<ClaimCheckStoredPayload<object>?>(stored));

        var ctx = new WorkflowContext();
        ctx.Properties[ClaimCheckStep.ClaimTicketKey] = "t";
        var sut = new ClaimRetrieveStep(store, "myResult");
        await sut.ExecuteAsync(ctx);

        await Given("context after retrieve with custom key 'myResult'", () => ctx)
            .Then("payload is under 'myResult'", c =>
            {
                c.Properties["myResult"].Should().Be(payload);
                return true;
            })
            .AssertPassed();
    }

    [Scenario("ClaimRetrieveStep throws when no ticket on context"), Fact]
    public async Task ClaimRetrieveNoTicketThrows()
    {
        // Characterization: when ClaimTicketKey is missing from context.Properties the
        // dictionary indexer throws KeyNotFoundException (not InvalidOperationException).
        // InvalidOperationException is only thrown when the key exists but casts to null.
        var store = Substitute.For<IClaimCheckStore<object>>();
        var sut = new ClaimRetrieveStep(store);
        var ctx = new WorkflowContext(); // no ticket set

        Exception? caught = null;
        try { await sut.ExecuteAsync(ctx); }
        catch (Exception ex) { caught = ex; }

        await Given("exception when ClaimTicketKey is absent from context", () => caught)
            .Then("an exception is thrown (KeyNotFoundException from missing dictionary key)", ex =>
            {
                ex.Should().NotBeNull();
                ex.Should().BeOfType<KeyNotFoundException>();
                return true;
            })
            .AssertPassed();
    }

    [Scenario("ClaimRetrieveStep throws InvalidOperationException when ticket key exists but is null"), Fact]
    public async Task ClaimRetrieveNullTicketThrows()
    {
        var store = Substitute.For<IClaimCheckStore<object>>();
        var sut = new ClaimRetrieveStep(store);
        var ctx = new WorkflowContext();
        ctx.Properties[ClaimCheckStep.ClaimTicketKey] = null!; // key present but null

        Exception? caught = null;
        try { await sut.ExecuteAsync(ctx); }
        catch (InvalidOperationException ex) { caught = ex; }

        await Given("exception when ClaimTicketKey is null", () => caught)
            .Then("InvalidOperationException mentions running ClaimCheckStep first", ex =>
            {
                ex.Should().NotBeNull();
                ex!.Message.Should().Contain("ClaimCheckStep");
                return true;
            })
            .AssertPassed();
    }
}
